#!/bin/bash

echo "🔄 Deploying Complete Usage Overview Fix..."
echo "=========================================="

# Check if we're in the right directory
if [ ! -f "src/components/billing/UsageOverview.tsx" ]; then
    echo "❌ Error: Please run this script from the project root directory"
    exit 1
fi

echo "✅ Found UsageOverview component"

echo ""
echo "📊 Applying comprehensive usage overview database fixes..."
echo "Please run the following SQL in your Supabase SQL Editor:"
echo ""
echo "--- COPY THIS SQL INTO SUPABASE SQL EDITOR ---"
cat fix_usage_overview_complete.sql
echo ""
echo "--- END OF SQL ---"

echo ""
echo "🎉 Usage Overview Fix deployment complete!"
echo ""
echo "📋 Manual steps required:"
echo "   1. Go to your Supabase project dashboard"
echo "   2. Navigate to SQL Editor"
echo "   3. Run the SQL script (fix_usage_overview_complete.sql)"
echo "   4. Verify the functions were created successfully"
echo ""
echo "🔧 What this update does:"
echo "   • Adds missing columns to usage_counters table"
echo "   • Creates refresh_usage() function for monthly auto-reset"
echo "   • Creates check_usage_limit() function for plan enforcement"
echo "   • Creates get_user_usage_summary() function for comprehensive data"
echo "   • Creates increment_usage_counter() function for usage tracking"
echo "   • Automatically resets usage counts every new month"
echo ""
echo "📊 New columns added:"
echo "   • month_start (tracks current month)"
echo "   • insights_count (AI Insights)"
echo "   • analytics_count (Analytics Reports)"
echo "   • reports_count (Detailed Reports)"
echo "   • created_at, updated_at (timestamps)"
echo ""
echo "🔄 Monthly Reset Logic:"
echo "   • Checks if month_start matches current month"
echo "   • If not, resets all counts to 0"
echo "   • Updates month_start to current month"
echo "   • Creates new record if none exists"
echo ""
echo "🎯 Plan Limits Enforced:"
echo "   • Free: 50 feedback, 10 insights, 10 analytics, 5 reports"
echo "   • Pro: 300 feedback, 50 insights, 100 analytics, 20 reports"
echo "   • Business: Unlimited for all features"
echo ""
echo "🧪 Testing:"
echo "   1. Go to your billing page"
echo "   2. Check that usage data loads correctly"
echo "   3. Verify monthly reset works (test with different dates)"
echo "   4. Check that business users show unlimited"
echo "   5. Test usage enforcement for each plan"
echo ""
echo "✨ Complete usage overview system is now active!"