#!/bin/bash

echo "🔧 Fixing usage_counters table error..."
echo "====================================="

echo "❌ Error: column 'month_start' does not exist"
echo ""
echo "This means the usage_counters table wasn't created properly."
echo "Let's fix this step by step:"
echo ""

echo "📋 Step-by-step fix:"
echo "1. Go to your Supabase project dashboard"
echo "2. Navigate to SQL Editor"
echo "3. Copy and paste the following SQL:"
echo ""
echo "--- COPY THIS SQL INTO SUPABASE SQL EDITOR ---"
cat fix_usage_counters_schema.sql
echo ""
echo "--- END OF SQL ---"
echo ""
echo "4. Click 'Run' to execute the SQL"
echo "5. Verify the table was created by running:"
echo ""
echo "   SELECT * FROM usage_counters LIMIT 1;"
echo ""
echo "✅ After running the SQL, the usage_counters table will be properly created"
echo "   with the correct 'month_start' column and all required fields."
echo ""
echo "🧪 Test the fix:"
echo "   - Try submitting feedback again"
echo "   - Check that the Edge Function works without errors"
echo "   - Verify usage tracking is working"
echo ""
echo "📊 Expected table structure:"
echo "   - id (UUID, Primary Key)"
echo "   - user_id (UUID, Foreign Key to auth.users)"
echo "   - month_start (DATE, NOT NULL)"
echo "   - feedback_count (INTEGER, DEFAULT 0)"
echo "   - created_at (TIMESTAMP WITH TIME ZONE)"
echo "   - updated_at (TIMESTAMP WITH TIME ZONE)"
echo "   - UNIQUE constraint on (user_id, month_start)"