#!/bin/bash

echo "🔧 Fixing Subscription Issues"
echo "=============================="
echo ""
echo "Based on the console errors, there are several issues:"
echo "1. 406 Error: user_subscriptions table access issue"
echo "2. 500 Error: usageTracking Edge Function failing"
echo "3. 403 Error: analytics_events table access denied"
echo ""
echo "📋 Steps to fix:"
echo ""
echo "1. Go to your Supabase Dashboard"
echo "2. Navigate to SQL Editor"
echo "3. Run the following SQL scripts in order:"
echo ""
echo "   a) First run: check_subscription_status.sql"
echo "   b) Then run: fix_usage_tracking_function.sql"
echo ""
echo "4. After running the SQL scripts, refresh your billing page"
echo ""
echo "📝 What these scripts do:"
echo "- Check if user_subscriptions table exists and has proper data"
echo "- Create a default subscription record for your user if missing"
echo "- Fix usage tracking data and functions"
echo "- Ensure all required tables and policies are working"
echo ""
echo "🚀 After running the scripts:"
echo "- The subscription should show 'Free Trial' instead of 'Unknown'"
echo "- Usage tracking should work properly"
echo "- Payment processing should update the subscription correctly"
echo ""
echo "Need help? Check the SQL script comments for detailed explanations."